import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import ClientProviders from "@/components/ClientProviders";
import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Pengeluarin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Meta tag untuk viewport */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/logoPengeluarin.png" />
      </head>

      <body className="bg-gray-100 text-gray-800 flex flex-col max-w-md min-h-screen mx-auto shadow-md">
        <Providers>
          <ClientProviders>
            <main className="min-h-screen flex flex-col w-full max-w-screen-sm mx-auto bg-sky-700 ">
              {children}
            </main>
          </ClientProviders>
        </Providers>
      </body>
    </html>
  );
}
